// Auto-generated by generate.ts

export { default as ArrowDownFilled } from './filled/arrows/arrow-down.svg';
export { default as ArrowLeftFilled } from './filled/arrows/arrow-left.svg';
export { default as ArrowRightFilled } from './filled/arrows/arrow-right.svg';
export { default as ArrowUpFilled } from './filled/arrows/arrow-up.svg';
export { default as ArrowDownOutlined } from './outlined/arrows/arrow-down.svg';
export { default as ArrowLeftOutlined } from './outlined/arrows/arrow-left.svg';
export { default as ArrowRightOutlined } from './outlined/arrows/arrow-right.svg';
export { default as ArrowUpOutlined } from './outlined/arrows/arrow-up.svg';
export { default as ArrowDownRounded } from './rounded/arrows/arrow-down.svg';
export { default as ArrowLeftRounded } from './rounded/arrows/arrow-left.svg';
export { default as ArrowRightRounded } from './rounded/arrows/arrow-right.svg';
export { default as ArrowUpRounded } from './rounded/arrows/arrow-up.svg';
export { default as ArrowDownSharp } from './sharp/arrows/arrow-down.svg';
export { default as ArrowLeftSharp } from './sharp/arrows/arrow-left.svg';
export { default as ArrowRightSharp } from './sharp/arrows/arrow-right.svg';
export { default as ArrowUpSharp } from './sharp/arrows/arrow-up.svg';
