/**
 * Qeetix token build.
 *
 * Single source (tokens/**) → three artifacts:
 *   dist/qeetix.css         — shadcn / Base-UI bridge (:root + .dark, UNPREFIXED vars)
 *   dist/qeetix.tokens.css  — full raw token export (--qx- prefixed)
 *   dist/qeetix.tokens.json — resolved tokens per theme (cross-platform)
 *
 * Light and dark are built as separate Style Dictionary instances (their token
 * names collide by design), then concatenated.
 */
import StyleDictionary from "style-dictionary";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const BUILD = join(ROOT, "build");
const DIST = join(ROOT, "dist");

// ---- custom formats ---------------------------------------------------------

StyleDictionary.registerFormat({
  name: "qeetix/css",
  format: ({ dictionary, options }) => {
    const selector = options.selector ?? ":root";
    const prefix = options.prefix ? `${options.prefix}-` : "";
    const lines = dictionary.allTokens.map(
      (t) => `  --${prefix}${t.path.join("-")}: ${t.$value};`,
    );
    return `${selector} {\n${lines.join("\n")}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: "qeetix/json",
  format: ({ dictionary }) => {
    const out = {};
    for (const t of dictionary.allTokens) {
      let node = out;
      t.path.forEach((seg, i) => {
        if (i === t.path.length - 1) node[seg] = t.$value;
        else node = node[seg] ??= {};
      });
    }
    return `${JSON.stringify(out, null, 2)}\n`;
  },
});

// ---- filters ----------------------------------------------------------------

const isBridge = (t) => t.filePath.includes("bridge");
const notBridge = (t) => !isBridge(t);
const themeOverride = (t) => t.filePath.includes(`${"/theme/"}`) && !isBridge(t);

// ---- per-theme instance -----------------------------------------------------

function sdForTheme(theme) {
  const selector = theme === "light" ? ":root" : ".dark";
  return new StyleDictionary({
    source: [
      join(ROOT, "tokens/primitive/**/*.json"),
      join(ROOT, `tokens/theme/${theme}/**/*.json`),
    ],
    log: { verbosity: "silent", warnings: "disabled" },
    platforms: {
      bridge: {
        buildPath: "build/",
        transforms: [],
        files: [
          {
            destination: `bridge-${theme}.css`,
            format: "qeetix/css",
            filter: isBridge,
            options: { selector },
          },
        ],
      },
      raw: {
        buildPath: "build/",
        transforms: [],
        files: [
          {
            destination: `raw-${theme}.css`,
            format: "qeetix/css",
            // light carries the primitives + semantic in :root; dark only the overrides.
            filter: theme === "light" ? notBridge : themeOverride,
            options: { selector, prefix: "qx" },
          },
        ],
      },
      json: {
        buildPath: "build/",
        transforms: [],
        files: [
          {
            destination: `tokens-${theme}.json`,
            format: "qeetix/json",
            filter: notBridge,
          },
        ],
      },
    },
  });
}

// ---- run --------------------------------------------------------------------

rmSync(BUILD, { recursive: true, force: true });
for (const theme of ["light", "dark"]) {
  await (await sdForTheme(theme)).buildAllPlatforms();
}

mkdirSync(DIST, { recursive: true });
const header =
  "/**\n * Qeetix design tokens — GENERATED by packages/tokens/build.mjs.\n" +
  " * Do not edit by hand. Edit tokens/** and rebuild (`pnpm --filter @qeetix/tokens build`).\n */\n";
const read = (f) => readFileSync(join(BUILD, f), "utf8");

writeFileSync(
  join(DIST, "qeetix.css"),
  `${header}\n${read("bridge-light.css")}\n${read("bridge-dark.css")}`,
);
writeFileSync(
  join(DIST, "qeetix.tokens.css"),
  `${header}\n${read("raw-light.css")}\n${read("raw-dark.css")}`,
);
writeFileSync(
  join(DIST, "qeetix.tokens.json"),
  `${JSON.stringify(
    {
      $description: "Qeetix design tokens, resolved per theme. Generated — do not edit.",
      light: JSON.parse(read("tokens-light.json")),
      dark: JSON.parse(read("tokens-dark.json")),
    },
    null,
    2,
  )}\n`,
);

console.log("✔ Qeetix tokens built → dist/qeetix.css, dist/qeetix.tokens.css, dist/qeetix.tokens.json");
